### ISSUE TITLE
404 Error when attempting to run application

### ISSUE THREAD

**Issue by SIsilicon** [DarkGamerYT/Bedrock-Tools#11]
**Describe the bug**
There's not much to say. I downloaded the latest beta at the time of writing, installed it, and ran it. Then I get a blank screen with the error text `{"statusCode":404,"error":"Not Found"}`.

**To Reproduce**
See above.

**Expected behavior**
Application starts up fine

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v0.1.1-beta

**Comment by xKingDark** [comment]
I published a new build [v0.1.2-beta](https://github.com/DarkGamerYT/Bedrock-Tools/releases/tag/v0.1.2-beta), could you try installing that one and see if the issue still occurs. Thanks!

**Comment by SIsilicon** [comment]
It works! Closing 👍
