### ISSUE TITLE
there is a comma in the id generator menu

### ISSUE THREAD

**Issue by smasherxs** [DarkGamerYT/Bedrock-Tools#14]
![image](https://github.com/DarkGamerYT/Bedrock-Tools/assets/130891399/29c078bb-8aee-4701-98cb-cb00f4548b73)

**Comment by SineVector241** [comment]
Wonder how that got there XD. I'll fix it later...

**Comment by xKingDark** [comment]
I just pushed a commit to remove the extra comma, you should no longer see it appearing in the next release (v0.1.4-beta)

**Comment by SineVector241** [comment]
Fixed in 263e0a47bcf88a711bccc747732378927a1598ea
