### ISSUE TITLE
how do I use it?

### ISSUE THREAD

**Issue by AveryWiggle** [DarkGamerYT/Bedrock-Tools#16]
Pls tell me how to use it..

**Comment by xKingDark** [comment]
There isn't a specific way of using Bedrock Tools, you can simply run it by either downloading the source and running `npm run start` or installing the latest version from [the releases tab](https://github.com/DarkGamerYT/Bedrock-Tools/releases)

**Comment by AveryWiggle** [comment]
can we use it for Iphones or Ipads?

**Comment by xKingDark** [comment]
Currently it's only available for Windows
